[toolchain]

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
staking_game_anchor = "8FjJrRvqdJhUtPt2hfBKMkhWkfpw73Yvucv2cFH9ouaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
